//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpdateRecordModule_SH_D.Properties {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UpdateRecordModule_SH_D.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap btnItemNameList_Image {
            get {
                object obj = ResourceManager.GetObject("btnItemNameList_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap btnItemNameList_Image1 {
            get {
                object obj = ResourceManager.GetObject("btnItemNameList_Image1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap demographic_reload_64 {
            get {
                object obj = ResourceManager.GetObject("demographic_reload_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Byte[] 的當地語系化資源。
        /// </summary>
        internal static byte[] EnrollmentListTemplate {
            get {
                object obj = ResourceManager.GetObject("EnrollmentListTemplate", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 (圖示) 的類型 System.Drawing.Icon 當地語系化資源。
        /// </summary>
        internal static System.Drawing.Icon error {
            get {
                object obj = ResourceManager.GetObject("error", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Byte[] 的當地語系化資源。
        /// </summary>
        internal static byte[] ExtendingGraduatingStudentListTemplate {
            get {
                object obj = ResourceManager.GetObject("ExtendingGraduatingStudentListTemplate", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Byte[] 的當地語系化資源。
        /// </summary>
        internal static byte[] ExtendingStudentListTemplate {
            get {
                object obj = ResourceManager.GetObject("ExtendingStudentListTemplate", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Byte[] 的當地語系化資源。
        /// </summary>
        internal static byte[] ExtendingStudentUpdateRecordListTemplate {
            get {
                object obj = ResourceManager.GetObject("ExtendingStudentUpdateRecordListTemplate", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Byte[] 的當地語系化資源。
        /// </summary>
        internal static byte[] GraduatingStudentListTemplate {
            get {
                object obj = ResourceManager.GetObject("GraduatingStudentListTemplate", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap history_save_64 {
            get {
                object obj = ResourceManager.GetObject("history_save_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;?xml-stylesheet type=&quot;text/xsl&quot; href=&quot;format.xsl&quot; ?&gt;
        ///&lt;ValidateRule Name=&quot;匯入新生異動&quot;&gt;
        ///  &lt;DuplicateDetection&gt;
        ///    &lt;Detector Name=&quot;PrimaryKey1&quot;&gt;
        ///      &lt;Field Name=&quot;學號&quot; /&gt;
        ///      &lt;Field Name=&quot;狀態&quot; /&gt;
        ///      &lt;Field Name=&quot;異動日期&quot; /&gt;
        ///      &lt;Field Name=&quot;異動代碼&quot; /&gt;
        ///    &lt;/Detector&gt;
        ///  &lt;/DuplicateDetection&gt;
        ///  &lt;FieldList&gt;
        ///    &lt;Field Required=&quot;True&quot; Name=&quot;學號&quot;&gt;
        ///      &lt;Validate AutoCorrect=&quot;False&quot; Description=&quot;「學號」不允許空白。&quot; ErrorType=&quot;Error&quot; Validator=&quot;不可空白&quot; When=&quot;&quot; /&gt;
        ///    &lt;/Field [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string ImportEnrollmentListVal {
            get {
                return ResourceManager.GetString("ImportEnrollmentListVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;?xml-stylesheet type=&quot;text/xsl&quot; href=&quot;format.xsl&quot; ?&gt;
        ///&lt;ValidateRule Name=&quot;匯入畢業異動&quot;&gt;
        ///  &lt;DuplicateDetection&gt;
        ///    &lt;Detector Name=&quot;PrimaryKey1&quot;&gt;
        ///      &lt;Field Name=&quot;學號&quot; /&gt;
        ///      &lt;Field Name=&quot;狀態&quot; /&gt;
        ///      &lt;Field Name=&quot;異動日期&quot; /&gt;
        ///      &lt;Field Name=&quot;異動代碼&quot; /&gt;
        ///    &lt;/Detector&gt;
        ///  &lt;/DuplicateDetection&gt;
        ///  &lt;FieldList&gt;
        ///    &lt;Field Required=&quot;True&quot; Name=&quot;學號&quot;&gt;
        ///      &lt;Validate AutoCorrect=&quot;False&quot; Description=&quot;「學號」不允許空白。&quot; ErrorType=&quot;Error&quot; Validator=&quot;不可空白&quot; When=&quot;&quot; /&gt;
        ///    &lt;/Field [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string ImportGraduateListVal {
            get {
                return ResourceManager.GetString("ImportGraduateListVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;?xml-stylesheet type=&quot;text/xsl&quot; href=&quot;format.xsl&quot; ?&gt;
        ///&lt;ValidateRule Name=&quot;匯入學籍異動&quot;&gt;
        ///  &lt;DuplicateDetection&gt;
        ///    &lt;Detector Name=&quot;PrimaryKey1&quot;&gt;
        ///      &lt;Field Name=&quot;學號&quot; /&gt;
        ///      &lt;Field Name=&quot;狀態&quot; /&gt;
        ///      &lt;Field Name=&quot;異動日期&quot; /&gt;
        ///      &lt;Field Name=&quot;異動代碼&quot; /&gt;
        ///    &lt;/Detector&gt;
        ///  &lt;/DuplicateDetection&gt;
        ///  &lt;FieldList&gt;
        ///    &lt;Field Required=&quot;True&quot; Name=&quot;學號&quot;&gt;
        ///      &lt;Validate AutoCorrect=&quot;False&quot; Description=&quot;「學號」不允許空白。&quot; ErrorType=&quot;Error&quot; Validator=&quot;不可空白&quot; When=&quot;&quot; /&gt;
        ///    &lt;/Field [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string ImportStudUpdateRecordListVal {
            get {
                return ResourceManager.GetString("ImportStudUpdateRecordListVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;?xml-stylesheet type=&quot;text/xsl&quot; href=&quot;format.xsl&quot; ?&gt;
        ///&lt;ValidateRule Name=&quot;匯入轉入異動&quot;&gt;
        ///  &lt;DuplicateDetection&gt;
        ///    &lt;Detector Name=&quot;PrimaryKey1&quot;&gt;
        ///      &lt;Field Name=&quot;學號&quot; /&gt;
        ///      &lt;Field Name=&quot;狀態&quot; /&gt;
        ///      &lt;Field Name=&quot;異動日期&quot; /&gt;
        ///      &lt;Field Name=&quot;異動代碼&quot; /&gt;
        ///    &lt;/Detector&gt;
        ///  &lt;/DuplicateDetection&gt;
        ///  &lt;FieldList&gt;
        ///    &lt;Field Required=&quot;True&quot; Name=&quot;學號&quot;&gt;
        ///      &lt;Validate AutoCorrect=&quot;False&quot; Description=&quot;「學號」不允許空白。&quot; ErrorType=&quot;Error&quot; Validator=&quot;不可空白&quot; When=&quot;&quot; /&gt;
        ///    &lt;/Field [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string ImportTransferListVal {
            get {
                return ResourceManager.GetString("ImportTransferListVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;國中代碼&gt;
        ///	&lt;學校 代碼=&quot;011503&quot; 名稱=&quot;私立裕德國中(小)&quot; 所在地=&quot;新北市&quot; 所在地代碼=&quot;1&quot;/&gt;
        ///	&lt;學校 代碼=&quot;014501&quot; 名稱=&quot;市立板橋國中&quot; 所在地=&quot;新北市&quot; 所在地代碼=&quot;1&quot;/&gt;
        ///	&lt;學校 代碼=&quot;014503&quot; 名稱=&quot;市立重慶國中&quot; 所在地=&quot;新北市&quot; 所在地代碼=&quot;1&quot;/&gt;
        ///	&lt;學校 代碼=&quot;014504&quot; 名稱=&quot;市立江翠國中&quot; 所在地=&quot;新北市&quot; 所在地代碼=&quot;1&quot;/&gt;
        ///	&lt;學校 代碼=&quot;014505&quot; 名稱=&quot;市立中山國中&quot; 所在地=&quot;新北市&quot; 所在地代碼=&quot;1&quot;/&gt;
        ///	&lt;學校 代碼=&quot;014506&quot; 名稱=&quot;市立新埔國中&quot; 所在地=&quot;新北市&quot; 所在地代碼=&quot;1&quot;/&gt;
        ///	&lt;學校 代碼=&quot;014507&quot; 名稱=&quot;市立新莊國中&quot; 所在地=&quot;新北市&quot; 所在地代碼=&quot;1&quot;/&gt;
        ///	&lt;學校 代碼=&quot;014508&quot; 名稱=&quot;市立新泰國中&quot; 所在地=&quot;新北市&quot; 所在地代碼=&quot;1&quot;/&gt;
        ///	&lt;學校 代碼=&quot;014509&quot; 名稱=&quot;市立福營國中&quot; 所在地=&quot;新北市&quot; 所在地代碼= [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string JHSchoolList {
            get {
                return ResourceManager.GetString("JHSchoolList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Byte[] 的當地語系化資源。
        /// </summary>
        internal static byte[] RetaintoStudentListTemplate {
            get {
                object obj = ResourceManager.GetObject("RetaintoStudentListTemplate", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;高中代碼&gt;
        ///  &lt;學校 代碼=&quot;010301&quot; 名稱=&quot;國立華僑中學&quot; 所在地=&quot;新北市&quot; 所在地代碼=&quot;1&quot;/&gt;
        ///  &lt;學校 代碼=&quot;011301&quot; 名稱=&quot;私立淡江高中&quot; 所在地=&quot;新北市&quot; 所在地代碼=&quot;1&quot;/&gt;
        ///  &lt;學校 代碼=&quot;011302&quot; 名稱=&quot;私立康橋高中&quot; 所在地=&quot;新北市&quot; 所在地代碼=&quot;1&quot;/&gt;
        ///  &lt;學校 代碼=&quot;011306&quot; 名稱=&quot;私立金陵女中&quot; 所在地=&quot;新北市&quot; 所在地代碼=&quot;1&quot;/&gt;
        ///  &lt;學校 代碼=&quot;011309&quot; 名稱=&quot;財團法人南山高中&quot; 所在地=&quot;新北市&quot; 所在地代碼=&quot;1&quot;/&gt;
        ///  &lt;學校 代碼=&quot;011310&quot; 名稱=&quot;財團法人恆毅高中&quot; 所在地=&quot;新北市&quot; 所在地代碼=&quot;1&quot;/&gt;
        ///  &lt;學校 代碼=&quot;011311&quot; 名稱=&quot;私立聖心女中&quot; 所在地=&quot;新北市&quot; 所在地代碼=&quot;1&quot;/&gt;
        ///  &lt;學校 代碼=&quot;011312&quot; 名稱=&quot;私立崇義高中&quot; 所在地=&quot;新北市&quot; 所在地代碼=&quot;1&quot;/&gt;
        ///  &lt;學校 代碼=&quot;011314&quot; 名稱=&quot;財團法人中華高中&quot; 所在地= [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string SHSchoolList {
            get {
                return ResourceManager.GetString("SHSchoolList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Byte[] 的當地語系化資源。
        /// </summary>
        internal static byte[] StudentUpdateRecordListTemplate {
            get {
                object obj = ResourceManager.GetObject("StudentUpdateRecordListTemplate", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Byte[] 的當地語系化資源。
        /// </summary>
        internal static byte[] TemporaryStudentListTemplate {
            get {
                object obj = ResourceManager.GetObject("TemporaryStudentListTemplate", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Byte[] 的當地語系化資源。
        /// </summary>
        internal static byte[] TransferringStudentUpdateRecordListTemplate {
            get {
                object obj = ResourceManager.GetObject("TransferringStudentUpdateRecordListTemplate", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;異動代號對照表&gt;
        ///  &lt;異動&gt;
        ///    &lt;代號&gt;001&lt;/代號&gt;
        ///    &lt;原因及事項&gt;持國民中學畢業證書者(含國中補校)&lt;/原因及事項&gt;
        ///    &lt;分類&gt;新生異動&lt;/分類&gt;
        ///  &lt;/異動&gt;
        ///  &lt;異動&gt;
        ///    &lt;代號&gt;002&lt;/代號&gt;
        ///    &lt;原因及事項&gt;持國民中學補習學校資格證明書者&lt;/原因及事項&gt;
        ///    &lt;分類&gt;新生異動&lt;/分類&gt;
        ///  &lt;/異動&gt;
        ///  &lt;異動&gt;
        ///    &lt;代號&gt;003&lt;/代號&gt;
        ///    &lt;原因及事項&gt;持國民中學補習學校結(修)業證明書者&lt;/原因及事項&gt;
        ///    &lt;分類&gt;新生異動&lt;/分類&gt;
        ///  &lt;/異動&gt;
        ///  &lt;異動&gt;
        ///    &lt;代號&gt;004&lt;/代號&gt;
        ///    &lt;原因及事項&gt;持國民中學修業證明書者(修習三年級課程)&lt;/原因及事項&gt;
        ///    &lt;分類&gt;新生異動&lt;/分類&gt;
        ///  &lt;/異動&gt;
        ///  &lt;異動&gt;
        ///    &lt;代號&gt;005&lt;/代號&gt;
        ///    &lt;原因及事項&gt;持國民中學畢業程度學力鑑定考試及格證明書者&lt;/原因及事項&gt;
        ///    &lt;分類&gt;新生異動&lt;/分類&gt;
        ///  &lt;/ [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string UpdateCode_SHD {
            get {
                return ResourceManager.GetString("UpdateCode_SHD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 (圖示) 的類型 System.Drawing.Icon 當地語系化資源。
        /// </summary>
        internal static System.Drawing.Icon warning {
            get {
                object obj = ResourceManager.GetObject("warning", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
