//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpdateRecordModule_SH_N.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UpdateRecordModule_SH_N.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap btnItemNameList_Image {
            get {
                object obj = ResourceManager.GetObject("btnItemNameList_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap demographic_reload_64 {
            get {
                object obj = ResourceManager.GetObject("demographic_reload_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] EnrollmentListTemplate {
            get {
                object obj = ResourceManager.GetObject("EnrollmentListTemplate", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Icon error {
            get {
                object obj = ResourceManager.GetObject("error", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static byte[] ExtendingGraduatingStudentListTemplate {
            get {
                object obj = ResourceManager.GetObject("ExtendingGraduatingStudentListTemplate", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ExtendingStudentListTemplate {
            get {
                object obj = ResourceManager.GetObject("ExtendingStudentListTemplate", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] ExtendingStudentUpdateRecordListTemplate {
            get {
                object obj = ResourceManager.GetObject("ExtendingStudentUpdateRecordListTemplate", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] GraduatingStudentListTemplate {
            get {
                object obj = ResourceManager.GetObject("GraduatingStudentListTemplate", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap history_save_64 {
            get {
                object obj = ResourceManager.GetObject("history_save_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;?xml-stylesheet type=&quot;text/xsl&quot; href=&quot;format.xsl&quot; ?&gt;
        ///&lt;ValidateRule Name=&quot;匯入新生異動&quot;&gt;
        ///  &lt;DuplicateDetection&gt;
        ///    &lt;Detector Name=&quot;PrimaryKey1&quot;&gt;
        ///      &lt;Field Name=&quot;學號&quot; /&gt;
        ///      &lt;Field Name=&quot;狀態&quot; /&gt;
        ///      &lt;Field Name=&quot;異動日期&quot; /&gt;
        ///      &lt;Field Name=&quot;異動代碼&quot; /&gt;
        ///    &lt;/Detector&gt;
        ///  &lt;/DuplicateDetection&gt;
        ///  &lt;FieldList&gt;
        ///    &lt;Field Required=&quot;True&quot; Name=&quot;學號&quot;&gt;
        ///      &lt;Validate AutoCorrect=&quot;False&quot; Description=&quot;「學號」不允許空白。&quot; ErrorType=&quot;Error&quot; Validator=&quot;不可空白&quot; When=&quot;&quot; /&gt;
        ///    &lt;/Field [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ImportEnrollmentListVal {
            get {
                return ResourceManager.GetString("ImportEnrollmentListVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;?xml-stylesheet type=&quot;text/xsl&quot; href=&quot;format.xsl&quot; ?&gt;
        ///&lt;ValidateRule Name=&quot;匯入畢業異動&quot;&gt;
        ///  &lt;DuplicateDetection&gt;
        ///    &lt;Detector Name=&quot;PrimaryKey1&quot;&gt;
        ///      &lt;Field Name=&quot;學號&quot; /&gt;
        ///      &lt;Field Name=&quot;狀態&quot; /&gt;
        ///      &lt;Field Name=&quot;異動日期&quot; /&gt;
        ///      &lt;Field Name=&quot;異動代碼&quot; /&gt;
        ///    &lt;/Detector&gt;
        ///  &lt;/DuplicateDetection&gt;
        ///  &lt;FieldList&gt;
        ///    &lt;Field Required=&quot;True&quot; Name=&quot;學號&quot;&gt;
        ///      &lt;Validate AutoCorrect=&quot;False&quot; Description=&quot;「學號」不允許空白。&quot; ErrorType=&quot;Error&quot; Validator=&quot;不可空白&quot; When=&quot;&quot; /&gt;
        ///    &lt;/Field [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ImportGraduateListVal {
            get {
                return ResourceManager.GetString("ImportGraduateListVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;?xml-stylesheet type=&quot;text/xsl&quot; href=&quot;format.xsl&quot; ?&gt;
        ///&lt;ValidateRule Name=&quot;匯入學籍異動&quot;&gt;
        ///  &lt;DuplicateDetection&gt;
        ///    &lt;Detector Name=&quot;PrimaryKey1&quot;&gt;
        ///      &lt;Field Name=&quot;學號&quot; /&gt;
        ///      &lt;Field Name=&quot;狀態&quot; /&gt;
        ///      &lt;Field Name=&quot;異動日期&quot; /&gt;
        ///      &lt;Field Name=&quot;異動代碼&quot; /&gt;
        ///    &lt;/Detector&gt;
        ///  &lt;/DuplicateDetection&gt;
        ///  &lt;FieldList&gt;
        ///    &lt;Field Required=&quot;True&quot; Name=&quot;學號&quot;&gt;
        ///      &lt;Validate AutoCorrect=&quot;False&quot; Description=&quot;「學號」不允許空白。&quot; ErrorType=&quot;Error&quot; Validator=&quot;不可空白&quot; When=&quot;&quot; /&gt;
        ///    &lt;/Field [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ImportStudUpdateRecordListVal {
            get {
                return ResourceManager.GetString("ImportStudUpdateRecordListVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;?xml-stylesheet type=&quot;text/xsl&quot; href=&quot;format.xsl&quot; ?&gt;
        ///&lt;ValidateRule Name=&quot;匯入轉入異動&quot;&gt;
        ///  &lt;DuplicateDetection&gt;
        ///    &lt;Detector Name=&quot;PrimaryKey1&quot;&gt;
        ///      &lt;Field Name=&quot;學號&quot; /&gt;
        ///      &lt;Field Name=&quot;狀態&quot; /&gt;
        ///      &lt;Field Name=&quot;異動日期&quot; /&gt;
        ///      &lt;Field Name=&quot;異動代碼&quot; /&gt;
        ///    &lt;/Detector&gt;
        ///  &lt;/DuplicateDetection&gt;
        ///  &lt;FieldList&gt;
        ///    &lt;Field Required=&quot;True&quot; Name=&quot;學號&quot;&gt;
        ///      &lt;Validate AutoCorrect=&quot;False&quot; Description=&quot;「學號」不允許空白。&quot; ErrorType=&quot;Error&quot; Validator=&quot;不可空白&quot; When=&quot;&quot; /&gt;
        ///    &lt;/Field [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ImportTransferListVal {
            get {
                return ResourceManager.GetString("ImportTransferListVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;國中代碼&gt;
        ///  &lt;學校 代碼=&quot;011501&quot; 名稱=&quot;私立時雨國中&quot; 所在地=&quot;新北市&quot; 所在地代碼=&quot;01&quot; /&gt;
        ///  &lt;學校 代碼=&quot;014501&quot; 名稱=&quot;市立板橋國中&quot; 所在地=&quot;新北市&quot; 所在地代碼=&quot;01&quot; /&gt;
        ///  &lt;學校 代碼=&quot;014503&quot; 名稱=&quot;市立重慶國中&quot; 所在地=&quot;新北市&quot; 所在地代碼=&quot;01&quot; /&gt;
        ///  &lt;學校 代碼=&quot;014504&quot; 名稱=&quot;市立江翠國中&quot; 所在地=&quot;新北市&quot; 所在地代碼=&quot;01&quot; /&gt;
        ///  &lt;學校 代碼=&quot;014505&quot; 名稱=&quot;市立中山國中&quot; 所在地=&quot;新北市&quot; 所在地代碼=&quot;01&quot; /&gt;
        ///  &lt;學校 代碼=&quot;014506&quot; 名稱=&quot;市立新埔國中&quot; 所在地=&quot;新北市&quot; 所在地代碼=&quot;01&quot; /&gt;
        ///  &lt;學校 代碼=&quot;014507&quot; 名稱=&quot;市立新莊國中&quot; 所在地=&quot;新北市&quot; 所在地代碼=&quot;01&quot; /&gt;
        ///  &lt;學校 代碼=&quot;014508&quot; 名稱=&quot;市立新泰國中&quot; 所在地=&quot;新北市&quot; 所在地代碼=&quot;01&quot; /&gt;
        ///  &lt;學校 代碼=&quot;014509&quot; 名稱=&quot;市立 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string JHSchoolList {
            get {
                return ResourceManager.GetString("JHSchoolList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;高中代碼&gt;
        ///  &lt;學校 代碼=&quot;010301&quot; 名稱=&quot;國立華僑中學&quot; 所在地=&quot;新北市&quot; 所在地代碼=&quot;01&quot; /&gt;
        ///  &lt;學校 代碼=&quot;010303&quot; 名稱=&quot;國立泰山高中&quot; 所在地=&quot;新北市&quot; 所在地代碼=&quot;01&quot; /&gt;
        ///  &lt;學校 代碼=&quot;010304&quot; 名稱=&quot;國立板橋高中&quot; 所在地=&quot;新北市&quot; 所在地代碼=&quot;01&quot; /&gt;
        ///  &lt;學校 代碼=&quot;010335&quot; 名稱=&quot;國立新店高中&quot; 所在地=&quot;新北市&quot; 所在地代碼=&quot;01&quot; /&gt;
        ///  &lt;學校 代碼=&quot;010336&quot; 名稱=&quot;國立中和高中&quot; 所在地=&quot;新北市&quot; 所在地代碼=&quot;01&quot; /&gt;
        ///  &lt;學校 代碼=&quot;010337&quot; 名稱=&quot;國立新莊高中&quot; 所在地=&quot;新北市&quot; 所在地代碼=&quot;01&quot; /&gt;
        ///  &lt;學校 代碼=&quot;010338&quot; 名稱=&quot;國立三重高中&quot; 所在地=&quot;新北市&quot; 所在地代碼=&quot;01&quot; /&gt;
        ///  &lt;學校 代碼=&quot;010339&quot; 名稱=&quot;國立林口高中&quot; 所在地=&quot;新北市&quot; 所在地代碼=&quot;01&quot; /&gt;
        ///  &lt;學校 代碼=&quot;011301&quot; 名稱=&quot;私立 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SHSchoolList {
            get {
                return ResourceManager.GetString("SHSchoolList", resourceCulture);
            }
        }
        
        internal static byte[] StudentUpdateRecordListTemplate {
            get {
                object obj = ResourceManager.GetObject("StudentUpdateRecordListTemplate", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] TransferringStudentUpdateRecordListTemplate {
            get {
                object obj = ResourceManager.GetObject("TransferringStudentUpdateRecordListTemplate", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;異動代號對照表&gt;
        ///  &lt;異動&gt;
        ///    &lt;代號&gt;001&lt;/代號&gt;
        ///    &lt;原因及事項&gt;持國民中學畢業證書者&lt;/原因及事項&gt;
        ///    &lt;分類&gt;新生異動&lt;/分類&gt;
        ///  &lt;/異動&gt;
        ///  &lt;異動&gt;
        ///    &lt;代號&gt;002&lt;/代號&gt;
        ///    &lt;原因及事項&gt;持國民中學補習學校資格證明書者&lt;/原因及事項&gt;
        ///    &lt;分類&gt;新生異動&lt;/分類&gt;
        ///  &lt;/異動&gt;
        ///  &lt;異動&gt;
        ///    &lt;代號&gt;003&lt;/代號&gt;
        ///    &lt;原因及事項&gt;持國民中學補習學校結業證明書者&lt;/原因及事項&gt;
        ///    &lt;分類&gt;新生異動&lt;/分類&gt;
        ///  &lt;/異動&gt;
        ///  &lt;異動&gt;
        ///    &lt;代號&gt;004&lt;/代號&gt;
        ///    &lt;原因及事項&gt;持國民中學修(結)業證明書者(需於備註欄註明『修滿三學年課程』)&lt;/原因及事項&gt;
        ///    &lt;分類&gt;新生異動&lt;/分類&gt;
        ///  &lt;/異動&gt;
        ///  &lt;異動&gt;
        ///    &lt;代號&gt;005&lt;/代號&gt;
        ///    &lt;原因及事項&gt;持國中畢業程度學力鑑定考試及格證明書者&lt;/原因及事項&gt;
        ///    &lt;分類&gt;新生異動&lt;/分類&gt;
        ///  &lt;/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UpdateCode_SHN {
            get {
                return ResourceManager.GetString("UpdateCode_SHN", resourceCulture);
            }
        }
        
        internal static System.Drawing.Icon warning {
            get {
                object obj = ResourceManager.GetObject("warning", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static byte[] 新生學生名冊_進校 {
            get {
                object obj = ResourceManager.GetObject("新生學生名冊_進校", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] 畢業學生名冊_進校 {
            get {
                object obj = ResourceManager.GetObject("畢業學生名冊_進校", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] 異動學生名冊_進校 {
            get {
                object obj = ResourceManager.GetObject("異動學生名冊_進校", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] 轉入學生名冊_進校 {
            get {
                object obj = ResourceManager.GetObject("轉入學生名冊_進校", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
